### ISSUE TITLE
Crypto Project Part 1: Features required

### ISSUE THREAD

**Issue by dapinkone** [dapinkone/TCSS487Project#1]
###  Part 1
https://nvlpubs.nist.gov/nistpubs/SpecialPublications/NIST.SP.800-185.pdf [SHA-3 Derived functions cSHAKE, KMAC, TupleHash, ParallelHash]
https://nvlpubs.nist.gov/nistpubs/fips/nist.fips.202.pdf [SHA-3 Standard]
- [x] Keccak
  - [x] KMACXOF256
    - [x] bytepad
    - [x] encode_string
    - [x] #3
    - [x] right_encode
    - [x] ~~substring~~
  - [x] keccak core algorithm
  
- [x] cSHAKE256 and KMACXOF256
  - [x] #2
---
Specific requirements from rubric:
- [x] command-line application/interface, using ` the String[] args argument to the main() in Main.java` 
- [x] compute plain cryptographic hash of a given file(or text input by user)
  - [x] requires implementing/testing cSHAKE256, KMACXOF256
- [x] compute authentication tag (MAC) of a given file(or user-given input) under a given passphrase
- [x] encrypt a given data file symmetrically under a given passphrase
- [x] decrypt a given symmetric cryptogram under a given passphrase

- [x] Instructions / documentation for use of the application should be typeset and provided in project report PDF

**Comment by dapinkone** [comment]
part 1 requirements complete.
